package ca.bc.gov.common.const

const val SERVER_ERROR = 2000
const val SERVER_ERROR_DATA_MISMATCH = 2001
const val SERVER_ERROR_INCORRECT_PHN = 2002

const val MUST_QUEUED = 3000

const val DATABASE_ERROR = 4000

const val AUTH_ERROR = 5000
const val AUTH_ERROR_DO_LOGIN = 5001

const val MESSAGE_INVALID_RESPONSE = "Invalid response"

const val PROTECTIVE_WORD_ERROR_CODE = 6000
const val NETWORK_CONNECTION_ERROR_CODE = 7000

const val MUST_CALL_MOBILE_CONFIG = 8000

const val SERVICE_NOT_AVAILABLE = 9000
